### ISSUE TITLE
adb: error: cannot stat 'xxx/DroidBot-GPT/droidbot/resources/minicap/jni/libs/android-34/arm64-v8a/minicap.so': No such file or directory

### ISSUE THREAD

**Issue by IcyFeather233** [MobileLLM/AutoDroid#20]
# Env

- Python 3.8

# Running Command

The same apk and the same task_description as the [tech report](https://arxiv.org/pdf/2304.07061)

<img width="721" alt="image" src="https://github.com/user-attachments/assets/6a0fb09b-9c77-442a-bca3-8fa4253d7798">

```
python start.py -a ./apk/com.simplemobiletools.contacts.pro_107.apk -o output_dir -task "create a contact named Alice with number 1234567 and email alice@github.com"
```

# Result

```
2024-10-21 23:32:44.822 | DEBUG    | androguard.core.axml:get_resource_dimen:1625 - Out of range dimension unit index for 4082892.0: 13
2024-10-21 23:32:44.823 | DEBUG    | androguard.core.axml:get_resource_dimen:1625 - Out of range dimension unit index for 4082892.0: 13
2024-10-21 23:32:44.823 | DEBUG    | androguard.core.axml:get_resource_dimen:1625 - Out of range dimension unit index for 4060610.0: 15
2024-10-21 23:32:45.007 | WARNING  | androguard.core.axml:_decode_bytes:283 - invalid decoded string length
INFO:DroidBot:Starting DroidBot
INFO:Device:waiting for device
ls: /data/local/tmp/minicap-devel: No such file or directory
ls: 2>/dev/null: No such file or directory
/Users/icyfeather/projects/DroidBot-GPT/droidbot/resources/minicap/l...nicap: 1 file pushed, 0 skipped. 274.7 MB/s (580128 bytes in 0.002s)
WARNING:Device:push_file file does not exist: /Users/icyfeather/projects/DroidBot-GPT/droidbot/resources/minicap/jni/libs/android-34/arm64-v8a/minicap.so
adb: error: cannot stat '/Users/icyfeather/projects/DroidBot-GPT/droidbot/resources/minicap/jni/libs/android-34/arm64-v8a/minicap.so': No such file or directory
Traceback (most recent call last):
  File "/Users/icyfeather/projects/DroidBot-GPT/droidbot/droidbot.py", line 142, in start
    self.device.set_up()
  File "/Users/icyfeather/projects/DroidBot-GPT/droidbot/device.py", line 143, in set_up
    adapter.set_up()
  File "/Users/icyfeather/projects/DroidBot-GPT/droidbot/adapter/minicap.py", line 83, in set_up
    device.push_file(local_file=minicap_so_path, remote_dir=self.remote_minicap_path)
  File "/Users/icyfeather/projects/DroidBot-GPT/droidbot/device.py", line 756, in push_file
    self.adb.run_cmd(["push", local_file, remote_dir])
  File "/Users/icyfeather/projects/DroidBot-GPT/droidbot/adapter/adb.py", line 68, in run_cmd
    r = subprocess.check_output(args).strip()
  File "/Users/icyfeather/anaconda3/envs/droidbot/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/icyfeather/anaconda3/envs/droidbot/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', '-s', '41607ffd', 'push', '/Users/icyfeather/projects/DroidBot-GPT/droidbot/resources/minicap/jni/libs/android-34/arm64-v8a/minicap.so', '/data/local/tmp/minicap-devel']' returned non-zero exit status 1.
[CONNECTION] ADB is disconnected
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
Please wait while uninstalling the app...
```

**Comment by zr4in** [comment]
https://github.com/MobileLLM/AutoDroid/commit/a5ef4006ea26497af7719605d20b9daf1e6fa722
If this can help you.
