### ISSUE TITLE
After setting up the environment, running /scripts/calendar.sh results in the following error

### ISSUE THREAD

**Issue by waynecanfly** [MobileLLM/AutoDroid#8]
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: hkunlp/instructor-xl
load INSTRUCTOR_Transformer
max_seq_length  512
INFO:sentence_transformers.SentenceTransformer:Use pytorch device: cpu
Traceback (most recent call last):
  File "/AutoDroid/droidbot/droidbot.py", line 104, in __init__
    self.input_manager = InputManager(
  File "/AutoDroid/droidbot/input_manager.py", line 64, in __init__
    self.policy = self.get_input_policy(device, app, master)
  File "/AutoDroid/droidbot/input_manager.py", line 84, in get_input_policy
    input_policy = TaskPolicy(device, app, self.random_input, task=self.task)
  File "/AutoDroid/droidbot/input_policy.py", line 683, in __init__
    self.similar_ele_path, self.similar_ele_function, self.similar_ele_statement = self.get_most_similar_element()
  File "/AutoDroid/droidbot/input_policy.py", line 728, in get_most_similar_element
    similar_ele = ele_statements[app_name][similar_state_str]['elements'][similar_ele_idx]
TypeError: string indices must be integers
[CONNECTION] ADB is disconnected
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!

**Comment by wenh18** [comment]
I run the project locally and do not run into this error. You can check whether the memory/node_filtered_elements.json exists. If it still doesn't work, you can set use_memory=False in input_policy.py, which will avoid this bug but will disable the usage of explored app memory.
